services:
  plugin:
    build:
      context: .
    tty: true
    working_dir: /go/src/github.com/ZeroGachis/traefik-request-id
    volumes:
      - .:/go/src/github.com/ZeroGachis/traefik-request-id
